### ISSUE TITLE
strange linking problem, with libX11 on NixOS

### ISSUE THREAD

**Issue by amiloradovsky** [tomhrr/mawled#12]
While building, I get the following error:
```
dalec -c src/x11-xlib.dt
dalec -c src/workspace.dt
/tmp/nix-build-mawled-20170423.drv-0/mawled-1bd97af11fe3c44c9578f87a6f4eb5cfa88ca104-src/libx11-xlib.so: undefined symbol: XConfigureWindow
dalec: unable to load dynamic library
make: *** [Makefile:10: libworkspace.dtm] Error 1
```
But I'm not sure what that means:
Although  `libX11` is find-able, the command shouldn't care, since it's `-c`.
Even if I do specify the `-l` and `-L` flags, the result is just the same (the path is alive and does contain the file and the symbol).

I guess the problem may be with Dale and not particularly Mawled.

----------------
It seems like the compiler just ignores the `-c` flag when compiling `src/workplace.dt` -- present or not, the error is the same; while if we omit the flag when compiling `src/x11-xlib.dt` the error is just as expected (`undefined reference to 'main'`). Moreover, the same error arises when we just do `dalec -sas src/workspace.dt`.

BTW, it's not that any linking to external libraries doesn't work: `dalec -lglut eg/glut-example/glut-example.dt` works fine.

----------------
Narrowed the search space. -- It crashes on calling `generator.run` in `dalec.cpp`.
More specifically, on `FormTopLevelInstParse(&units, top);` inside `Generator::run`.

----------------
Here's where it fails, in Dale, in `src/dale/Form/TopLevel/Inst/Inst.cpp`:
```
    const char *form = form_token->str_value.c_str();
    bool (*toplevel_form)(Units *units, Node *n) =
        CoreForms::getTopLevel(form);
    if (toplevel_form) {
        toplevel_form(units, node);  /* <-- the point of failure */
        return true;
    }
```
But it's difficult to understand what's going on there.

----------------
It boils down to calling `llvm::sys::DynamicLibrary::LoadLibraryPermanently` from `Reader::addDynamicLibrary` in `src/dale/Module/Reader/Reader.cpp` with the file `<my-build-path>/mawled/libx11-xlib.so`, but why?

**Comment by amiloradovsky** [comment]
Added `-a /path/to/libX11.so` to the `dalec` flags, and it worked.
The generator wanted the `.so` file to be given as a compile library.
Now I'm looking how to handle this behavior properly (Nix+Mawled+Dale).

Here is one possible fix for Mawled itself:

- https://github.com/amiloradovsky/mawled/tree/libX11

Here is a hacky candidate for the NixOS port:

- https://github.com/amiloradovsky/nixpkgs/tree/mawled

And here's some refactoring of `dalec.cpp` I had to do in order to make a sense of it:

- https://github.com/amiloradovsky/dale/tree/dalec

**Comment by tomhrr** [comment]
Thanks for the report, and sorry about the delay here.  I can't replicate this issue on Debian (unstable) with LLVM 3.5.2: if the `-c` flag is passed when building `src/workspace.dt`, then compilation works as expected, and if it is not, errors about undefined symbols are seen.  The underlying LLVM code loads the relevant shared library using `dlopen` with the `RTLD_LAZY` flag, so the fact that those symbols are undefined shouldn't be causing problems at this stage, as far as I can tell.  I'll try to replicate this within NixOS and see if that leads anywhere.

**Comment by amiloradovsky** [comment]
It may be due to a hardening measure (which NixOS is full of): current Nixpkgs also has LLVM 3.5.2, with few patches, which do not appear to be affecting the "lazy" behavior of LLVM though.

https://github.com/NixOS/nixpkgs/tree/master/pkgs/development/compilers/llvm/3.5

**Comment by tomhrr** [comment]
Replicated on NixOS.  This doesn't appear to be LLVM-related: a test program that `dlopen`s the `libx11-xlib.so` library sees the same error message regardless of whether the mode is `RTLD_LAZY` or `RTLD_NOW`.  Still yet to figure out why this is happening.

**Comment by amiloradovsky** [comment]
[PatchELF](http://nixos.org/patchelf.html) may be to blame.

And here's someone experiencing similarly looking issue with dynamic linking:

- https://stackoverflow.com/questions/28329504/linux-dlerror-returning-error-message-from-dlopen-that-i-cant-explain

**Comment by tomhrr** [comment]
Tried a few other things, but still can't get it working.  Submitted https://github.com/NixOS/nixpkgs/issues/25796, hopefully the maintainers can give some pointers.

Regardless, the reliance on laziness here is a bit of a hack, so this will require more work in Dale proper.  Possible options include requiring all symbols to be resolvable at compile time, or being able to mark a module as 'runtime only' during compilation, such that its associated shared libraries are not loaded.

**Comment by tomhrr** [comment]
https://github.com/NixOS/nixpkgs/issues/25796 has the answer, which is that NixOS' compilation wrapper enables a series of default hardening options, including `-z now` as a linker flag.  When `-z now` is passed to the linker, the resulting shared library will be marked such that symbols are always resolved at load time.  `export hardeningDisable=bindnow` should allow for building to work properly (yet to confirm, having some environment issues).

**Comment by amiloradovsky** [comment]
Yes, I can confirm that it works on my system; here is how I applied the option:

https://github.com/NixOS/nixpkgs/compare/master...amiloradovsky:mawled

while giving it as an environment variable, either via `env` to `nix-shell` or via `export` inside it, will not work, for what I know.

PS: to install that on your system, use `nix-env -f <the-nixpkgs-tree> -iA mawled`

**Comment by jb55** [comment]
nix-build 'https://github.com/amiloradovsky/nixpkgs/archive/mawled.tar.gz' -Q -A mawled --no-out-link 

works! thanks for tracking this down.

**Comment by tomhrr** [comment]
It also now works for me.  Thanks again for the report, updates to Dale will follow.
