### ISSUE TITLE
The install dir(s) aren't properly created

### ISSUE THREAD

**Issue by amiloradovsky** [tomhrr/mawled#13]
The (`bin`) directory should be created before the installation into it or `install` should be called with `-D` flag:

https://github.com/amiloradovsky/nixpkgs/blob/mawled/pkgs/applications/window-managers/mawled/Makefile.patch

PS: this probably isn't worth a pull request but worth a separate issue; anyway, I'd like to drop the patch from the port, and, if you don't have an objections, try to merge it into Nixpkgs: any suggestions are welcome

**Comment by tomhrr** [comment]
Thanks, this has been updated.

**Comment by amiloradovsky** [comment]
Ok. The pull request it here:

https://github.com/NixOS/nixpkgs/pull/25858
